# Generated by Django 5.1.6 on 2025-04-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_cosmetics", "0003_cartitem_product_alter_cartitem_cart_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_images/"
            ),
        ),
    ]
